---
title: "Paisagens, história e diversidade: um panorama da sociobiodiversidade da Paraíba"
author: "Rômulo Romeu da Nóbrega Alves, Anna Karolina Martins Borges, Luana Ramos de Oliveira, Alexandre Vasconcellos"
format: html
---

# Aspectos históricos e geográficos

A formação territorial da Paraíba teve início em 1534, quando o Brasil Colônia foi dividido em Capitanias Hereditárias, grandes lotes de terra doados pela Coroa Portuguesa a membros da nobreza e aliados políticos. Nesse período, o território atualmente correspondente ao estado da Paraíba integrava a Capitania de Itamaracá, cuja extensão territorial ia desde a foz do rio Santa Cruz (atualmente Igarassu, em Pernambuco) até a Baía da Traição. Essa capitania foi inicialmente governada por Pero Lopes de Souza, que permaneceu à frente da administração até sua morte, em 1539. A conquista da região, no entanto, enfrentou fortes resistências, sobretudo dos povos indígenas Potiguaras, que se opunham aos avanços coloniais em defesa de seus territórios ancestrais.
