---
title: "Introdução"
author: Rômulo Romeu da Nóbrega Alves, Anna Karolina Martins Borges, Alexandre Vasconcellos
---




Somos animais e, como tal, compartilhamos características biológicas fundamentais com uma imensa diversidade de outras espécies, conectadas a nós por uma complexa rede de relações ecológicas e evolutivas. Como parte natural da fauna que habita a Terra, temos interagido com os animais ao nosso redor ao longo de nossa coexistência compartilhada, estabelecendo múltiplas inter-relações desde as origens de nossa espécie. Atividades como a caça, a pesca e a domesticação têm sido fundamentais para a subsistência humana ao longo do tempo, desempenhando um papel central na evolução cultural e biológica da nossa espécie. A natureza dinâmica dessas práticas, das mais ancestrais às mais contemporâneas, contribuiu para a multiplicidade de formas de interação entre seres humanos e animais. Sem dúvida, nossa identidade enquanto espécie foi profundamente moldada pelas relações que estabelecemos com os demais animais ao longo de nossa história compartilhada. 
